In [8]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
   
   $A_{4\times 2} \cdot B_{4\times 2}$ - Не определено 
   
   $B_{4\times 2} \cdot A_{4\times 2}$ - Не определено 
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
   
   $A_{2\times 5} \cdot B_{5\times 3} = C_{2\times 3} $
   
   $B_{5\times 3} \cdot A_{2\times 5}$ - Не определено 
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
   
   $A_{8\times 3} \cdot B_{3\times 8} = C_{8\times 8} $
   
   $B_{3\times 8} \cdot A_{8\times 3} = C_{3\times 3} $
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
   
   $A_{4\times 4} \cdot B_{4\times 4} = C_{4\times 4} $
   
   $B_{4\times 4} \cdot A_{4\times 4} = C_{4\times 4} $
    

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [12]:
A = np.matrix([[1, -2],
              [3, 0]])
B = np.matrix([[4, -1], 
              [0, 5]])


$ A + B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1+4 & -2+(-1)\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$


In [4]:
A + B 

matrix([[ 5, -3],
        [ 3,  5]])

$ A \cdot B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1\cdot4 + (-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\ 
3\cdot4 + 0\cdot0 & 3\cdot(-1)+0\cdot5 
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [10]:
A.dot(B)

matrix([[  4, -11],
        [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$

$2B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$

$4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}.$

$3A-2B+4C = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} -
\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} +
\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
3-0+8 & 21-10+(-16)\\ 
9-4+4 & -18-(-2)+4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [17]:
A = np.matrix([[1,7],
               [3,-6]])
B = np.matrix([[0,5],
               [2,-1]])
C = np.matrix([[2,-4],
               [1,-1]])

In [18]:
3*A, 2*B, 4*C

(matrix([[  3,  21],
         [  9, -18]]),
 matrix([[ 0, 10],
         [ 4, -2]]),
 matrix([[  8, -16],
         [  4,  -4]]))

In [19]:
3*A - 2*B + 4*C

matrix([[ 11,  -5],
        [  9, -20]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$.

In [20]:
A = np.matrix([[4,1],
               [5,-2],
               [2,3]])

In [21]:
A.T

matrix([[ 4,  5,  2],
        [ 1, -2,  3]])

$A\cdot A^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4 + 1\cdot1 & 4\cdot5 + 1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4 + (-2)\cdot1 & 5\cdot5 + (-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\ 
2\cdot4 + 3\cdot1 & 2\cdot5 + 3\cdot(-2) & 2\cdot2+3\cdot3 
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13 
\end{pmatrix} $ 

In [22]:
A.dot(A.T)

matrix([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]])

$A^{T}\cdot A=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4 + 5\cdot5 + 2\cdot2 & 4\cdot1 + 5\cdot(-2) + 2\cdot3\\ 
1\cdot4 + (-2)\cdot5 + 3\cdot2 & 1\cdot1 + (-2)\cdot(-2) + 3\cdot3
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14 
\end{pmatrix} $ 

In [24]:
A.T.dot(A)

matrix([[45,  0],
        [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [119]:
A = [[1,2,3],
     [4,5,6]]

In [120]:
B = [[1,2],
     [3,4],
     [5,6]]

In [134]:
def matrix_multiply(A,B):
    if len(A[0]) == len(B): #Проверка на возможность перемножения
    # Первым делом транспонируем вторую матрицу, так мне показалось будет проще потом перемножать их элементы
        B_col= [] # Здесь будет храниться транпонированная матрица В
        for j in range(len(B[0])):
            col = []  #сюда будем складывать вложенные списки-колонки матрицы B
            for i in range(len(B)):
                col.append(B[i][j])
            B_col.append(col)

        C = [] # Здесь будет храниться матрица C - результат перемножения матриц
        for i in A: #Перебираем элементы матрицы А
            row = []
            for j in B_col: #Перебираем элементы транспонированной матрицы В
                el = sum([a*b for a,b in zip(i, j)]) #Перемножаем элементы вложенных списков и находим их сумму
                row.append(el)
            C.append(row)
        return C
    else:
        print('Kоличество столбцов первой матрицы HE равно количеству строк второй матрицы. Умножение невозможно')
        
#Надо было еще проверить исключение,что если матрица записана как вектор(без вложенного списка), то работать не будет.Но будем считать что 
# надо записывать все вложенными списками, а то нет времени это продумывать

In [128]:
print(matrix_multiply(A,B))

[[22, 28], [49, 64]]


In [129]:
np.array(A).dot(np.array(B))

array([[22, 28],
       [49, 64]])

In [130]:
print(matrix_multiply(B,A))

[[9, 12, 15], [19, 26, 33], [29, 40, 51]]


In [131]:
np.array(B).dot(np.array(A))

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])