In [ ]:
import numpy as np
import scipy as sp

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    

In [ ]:
A = np.array([[1,-2], [3, -4]])

In [ ]:
np.linalg.det(A)

2.0000000000000004

In [ ]:
A1 = np.array([[1,7], [3, -4]])
A2 = np.array([[1,-2], [1, 7]])

In [ ]:
x1 = np.linalg.det(A1) / np.linalg.det(A)
x2 = np.linalg.det(A2) / np.linalg.det(A)

In [ ]:
print(f'x1 = {x1}\nx2 = {x2}\n')

x1 = -12.5
x2 = 4.5



   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [ ]:
A = np.array([[2, -1, 5], [1, -1, -3], [2, 4, 1]])

In [ ]:
np.linalg.det(A)

58.999999999999964

In [ ]:
A1 = np.array([[10, -2, 1], [1, -1, -3], [2, 4, 1]])
A2 = np.array([[2, -1, 5], [10, -2, 1], [2, 4, 1]])
A3 = np.array([[2, -1, 5], [1, -1, -3], [10, -2, 1]])

In [ ]:
np.linalg.det(A1)

130.00000000000009

In [ ]:
x1 = np.linalg.det(A1) / np.linalg.det(A)
x2 = np.linalg.det(A2) / np.linalg.det(A)
x3 = np.linalg.det(A3) / np.linalg.det(A)

In [ ]:
print(f'x1 = {x1}\nx2 = {x2}\nx3 = {x3}')

x1 = 2.203389830508477
x2 = 3.6610169491525455
x3 = 0.966101694915255


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

In [ ]:
from scipy.linalg import lu

In [ ]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
A

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

In [ ]:
print(f'L = \n\n{lu(A)[1]}')

L = 

[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [ ]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
A

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

In [ ]:
print(f'L = \n\n{lu(A)[1]}')

L = 

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [ ]:
from scipy.linalg import lu_factor, lu_solve

In [ ]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
A

array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])

In [ ]:
b = np.array([1, -6, -5])

In [ ]:
lu, piv = lu_factor(A)

In [ ]:
x = lu_solve((lu, piv), b)

In [ ]:
print(f'x1 = {x[0]}\nx2 = {x[1]}\nx3 = {x[2]}')

x1 = -1.0
x2 = 0.0
x3 = 1.0


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [ ]:
from scipy.linalg import cho_factor, cho_solve, cholesky

In [ ]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
A

array([[ 81, -45,  45],
       [-45,  50, -15],
       [ 45, -15,  38]])

In [ ]:
b = np.array([531, -460, 193])

In [ ]:
c, low = cho_factor(A)

In [ ]:
x = cho_solve((c, low), b)

In [ ]:
print(f'x1 = {x[0]}\nx2 = {x[1]}\nx3 = {x[2]}')

x1 = 6.0
x2 = -5.0
x3 = -4.0
